"""message

Revision ID: 45053863b605
Revises: 540f8bfbdaf4
Create Date: 2024-07-08 08:43:18.939074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45053863b605'
down_revision = '540f8bfbdaf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pizzas', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pizzas', 'ingredients',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('restaurant_pizzas', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.add_column('restaurant_pizzas', sa.Column('pizza_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_restaurant_pizzas_pizza_id_pizzas'), 'restaurant_pizzas', 'pizzas', ['pizza_id'], ['id'])
    op.create_foreign_key(op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), 'restaurant_pizzas', 'restaurants', ['restaurant_id'], ['id'])
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restaurants', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), 'restaurant_pizzas', type_='foreignkey')
    op.drop_constraint(op.f('fk_restaurant_pizzas_pizza_id_pizzas'), 'restaurant_pizzas', type_='foreignkey')
    op.drop_column('restaurant_pizzas', 'pizza_id')
    op.drop_column('restaurant_pizzas', 'restaurant_id')
    op.alter_column('pizzas', 'ingredients',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pizzas', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
