"""message

Revision ID: 5df7c9393928
Revises: 87b8bb3f2deb
Create Date: 2024-07-08 09:26:01.493302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df7c9393928'
down_revision = '87b8bb3f2deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
